# Generated by Django 5.0.2 on 2024-02-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('year', models.CharField(max_length=4, verbose_name='Year of hire')),
                ('salary', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Salary')),
            ],
            options={
                'permissions': (('can_view', 'View employees'), ('can_edit', 'Edit employees')),
            },
        ),
    ]
