# Generated by Django 5.0.2 on 2024-02-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=8, verbose_name='Salary'),
        ),
    ]
